title: "My Portfolio"
description: "A portfolio showcasing my work and writeups"
baseurl: "" # Adjust if hosted in a subdirectory
url: "https://sampath-code04.github.io"
theme: minima
collections:
  posts:
    output: true
    category: true
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
